### ISSUE TITLE
Add an option for copy/paste

### ISSUE THREAD

**Issue by fiery-transition** [PKM-er/obsidian-editing-toolbar#103]
**Is your feature request related to a problem? Please describe.**
When I select text that I want to copy, I get the toolbar to popup and hover over my selection, which gets in the way, since I then have to right click my selection which opens the default context menu as well, and then I can copy my selection.

**Describe the solution you'd like**
Add an option to have a copy and paste button inside the toolbar, so for quicker interaction and cleaner ux with fewer steps, I can use the toolbar to copy the selection directly.

**Describe alternatives you've considered**
You can't add copy selection as an action to the toolbar for some reason, since it's not a command in obsidian. I also thought about just pinning the toolbar to the top, but it would take valuable screen estate for me this way.

**Additional context**
This is mainly a nice ux improvement, where the amount of actions taken to copy the selected text would be reduced and less visual clutter would pop up (since right now, the toolbar is just in the way, when the only thing I want to do is copy some selected text, which is something most users do very often).

Thanks!

**Comment by cumany** [comment]
The new version has added the command
