### ISSUE TITLE
Content: 工具栏无法正常添加与修改子菜单😊，希望开发者重视完善修改这个BUG🔧。

### ISSUE THREAD

**Issue by 541864509proton** [PKM-er/obsidian-editing-toolbar#113]
**复制**
再现行为的步骤：
1.转到插件“设置”界面，在“在工具栏中添加命令”下方的列表区域。
2.拖到“Header2”到“Hn”这个组合菜单中。
3.错误：
a、程序后续无法继续通过拖动修改子菜单。
b、关闭“设置”界面后，再重新进入“设置”界面“Header2”并无成功添加到“Hn”这个组合菜单中。
**预期行为**
a、将“Header2”修改成“Hn”的子菜单。
b、自定义修改工具栏，将自己常用的命令添加到工具栏。

**Comment by h-ruii** [comment]
加一

**Comment by cumany** [comment]
下个版本修复
