### ISSUE TITLE
拖动设置项总失灵卡死

### ISSUE THREAD

**Issue by DanShui-Yu** [PKM-er/obsidian-editing-toolbar#114]
然后就一直拖动不了了

**Comment by iuuunlyk** [comment]
+1。
目前复现路径：在默认的submenu Hn子菜单进行拖拽进或者拖拽出的操作后，拖拽操作会失效（会卡死），任何拖拽都无法进行。除非重启obsidian可以恢复拖拽。

**Comment by cumany** [comment]
下个版本修复

**Comment by cumany** [comment]
This has been fixed in the new version
