### ISSUE TITLE
Mobile Support (Android) - Enhancement Suggestion

### ISSUE THREAD

**Issue by Cr8zyIvan** [PKM-er/obsidian-editing-toolbar#119]
**Is your feature request related to a problem? Please describe.**

I would love for Mobile (specifically Android) be supported by Editing Toolbar. More specifically, I am looking for an action/button for Format Eraser (Clear Text Formatting) on Mobile. Editing Toolbar is the only Plugin I've found that has this function for Desktop!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cumany** [comment]
Next version will support installation on mobile devices, but the styling may not match well
