### ISSUE TITLE
Plugin can not be loaded!

### ISSUE THREAD

**Issue by davebhc71** [PKM-er/obsidian-editing-toolbar#120]
Can Not load plugin 

See screen grab.

![IMG_0499](https://github.com/PKM-er/obsidian-editing-toolbar/assets/80698092/7cee8730-0349-4f1c-aa60-1a0fd86ad794)

 - OS: iPadOS17.2 Beta 2

 - Device: iPad10
 - OS: iPadOS17.2 Beta 2
 - Browser Safari

**Comment by PhoenixTan2** [comment]
Same problem.

OS: Windows 10 21H2 LTSC
Tool Version: 2.4.0

**Comment by cumany** [comment]
This has been fixed in the new version

**Comment by cumany** [comment]
This has been fixed in the new version
