### ISSUE TITLE
Cannot delete toolbar command on mobile (Android tablet)

### ISSUE THREAD

**Issue by witecat** [PKM-er/obsidian-editing-toolbar#121]
**Describe the bug**
Impossible to delete toolbar commands on mobile (Android tablet)

**To Reproduce**
1. Open settings
2. Go to Editing toolbar plugin settings
3. Try tapping on trash can icon to delete a command

**Expected behavior**
Tapping on trash can icon should delete command

**Screenshots**
No

**Desktop (please complete the following information):**
 - Android 13

**Smartphone (please complete the following information):**
 - Lenovo Tab P11 Plus
 - Android 13

**Comment by cumany** [comment]
This has been fixed in the new version
