### ISSUE TITLE
Cannot delete toolbar command on desktop

### ISSUE THREAD

**Issue by huachuman** [PKM-er/obsidian-editing-toolbar#122]
**Describe the bug**
I click the delete icon on any command. Nothing happens.

**To Reproduce**
see bug description

**Expected behavior**
see bug description

**Screenshots**
see bug description

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser ?????????????????????????????????????????????????????
 - Version latest non-catalyst

**Smartphone (please complete the following information):**
N/A

**Additional context**
You should update your bug report template. It is quite annoying.

**Comment by cumany** [comment]
新版本应该解决了这个问题
