### ISSUE TITLE
在ipad os16.1中不能成功安装enhanced-editing 0.6.4版本

### ISSUE THREAD

**Issue by greenvegetable** [PKM-er/obsidian-editing-toolbar#128]
**Describe the bug**
在ipad os16.1中不能成功安装obsidian-editing-toolbar  2.4.0  版本(the same as enhanced-editor)
 
![obsidianbug](https://github.com/PKM-er/obsidian-editing-toolbar/assets/18110591/2d445849-c143-475a-8197-013f61a78912)

**Comment by cumany** [comment]
This issue has been fixed, just update the plugin and enjoy!
