### ISSUE TITLE
Viewport visibility

### ISSUE THREAD

**Issue by dehahost** [PKM-er/obsidian-editing-toolbar#130]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
It would be great to have a control on which viewport (screen size) is the Editing toolbar visible or not. This could be extended with a toolbar position and so on.
For example ... one could configure it so that the Editing toolbar is visible on PC, on tablet is at the bottom and on mobile phone is hidden.

**Describe alternatives you've considered**
/ Enabling Editing toolbar plugin only when using a PC.
/ Not using Editing toolbar plugin.

**Additional context**
When I am taking a notes on my Android phone, I am used to the built-in editing toolbar. After the last update, I have two editing bars.

**Comment by cumany** [comment]
The new version has added relevant options
