### ISSUE TITLE
Toolbar on Android - Make optional for mobile

### ISSUE THREAD

**Issue by MikeSeim** [PKM-er/obsidian-editing-toolbar#131]
I noticed the toolbar is now available in mobile. Unfortunately, I've noticed it makes scrolling in my notes jumpy and problematic on my Android phone.

Frankly, I don't think the toolbar is needed on mobile as the built in mobile options are sufficient.

I would urge considering making the toolbar platform specific. If folks want it on their desktop, so be it. If they want it on android, so be it. If they don't, give them that option.

As it stands right now I can't have it on my Windows desktop without having it also on my Android. It's currently all or none.

**Comment by cumany** [comment]
The new version has added relevant options

**Comment by MikeSeim** [comment]
My goodness! You sure are fast and impressive. Thank you very much.

**Comment by MikeSeim** [comment]
Hey, I'm sorry to be a pain but the banner informing that it's off by default is sorta annoying on open. I'd urge dropping the notification that it's disabled by default.

**Comment by MikeSeim** [comment]
I've gone ahead and opened a new issue for this.
[Issue #168](https://github.com/PKM-er/obsidian-editing-toolbar/issues/168)
