### ISSUE TITLE
[bug] Failed to load plugin iOS 

### ISSUE THREAD

**Issue by Vexxent** [PKM-er/obsidian-editing-toolbar#133]
**Describe the bug**
Since iOS 17.3.1 plugin will not load, I have tested on two different vaults, reinstalled the plugin, and reinstalled the app. 

**To Reproduce**
1. Go to settings > community plugins 
2. attempt to enable editing-toolbar
3. Failed to load plugin

**Expected behavior**
The Plugin should enabled as it worked before updating. 

**Screenshots**
![IMG_4265](https://github.com/PKM-er/obsidian-editing-toolbar/assets/96324591/bbb66b7d-8703-47b1-a6bd-bba13dd4aada)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: 17.3.1
 - Browser: Safari

**Additional context**
Use iCloud for vault syncing and plugins were initially installed from desktop client

**Comment by emptinessboy** [comment]
我也遇到了相同的问题

**Comment by Vexxent** [comment]
Issue persists on iOS 17.4

**Comment by Michael-SD-Cali** [comment]
iPhone 14 Pro Max ver. 17.3.1 
I have the same issue.
![131CF591-CB34-4776-91C6-632CCB3D83FB](https://github.com/PKM-er/obsidian-editing-toolbar/assets/163979588/bd33eb26-c50c-4121-b31f-b00213ba6e93)

**Comment by Michael-SD-Cali** [comment]
iPhone 14 Pro Max ver. 17.3.1
I have the same issue.
![69CA052D-B1A4-4CFC-9883-047B3827F2BC](https://github.com/PKM-er/obsidian-editing-toolbar/assets/163979588/6a75c66c-5be6-4af5-abdb-0e5e6abcf42a)

**Comment by cumany** [comment]
This issue has been fixed, just update the plugin and enjoy!
