### ISSUE TITLE
请求适配thino编辑界面

### ISSUE THREAD

**Issue by linfengtongxue70** [PKM-er/obsidian-editing-toolbar#138]
开发者：

您好

Thino是一个比Flomo更好的基于obsidian笔记插件，非常适合用来记录灵感。今日我发现无法在obsidian thino的编辑界面使用editing toolbar插件，无法更好的修改笔记的格式。可能这有些冒昧，但还是想问下，未来会考虑适配obsidian thino的编辑界面吗？

请原谅我的冒犯，祝您生活愉快。

**Comment by cumany** [comment]
感谢反馈。下个版本即可支持

**Comment by juestchaos** [comment]
你可以试试最近的版本，貌似已经支持了
