### ISSUE TITLE
Inconsistent cursor type for the "following" and "fixed" position

### ISSUE THREAD

**Issue by s4my** [PKM-er/obsidian-editing-toolbar#144]
**Describe the bug**
When the position is set to "following" or "fixed", some buttons have the "default" cursor type, others the "pointer" type.

**Solution**
I don't think we should use the "pointer" type; Obsidian doesn't use it anywhere on any of its buttons. To respect the Obsidian design system, I think we shouldn't either, plus the "pointer" cursor is usually only used on web applications.

I am willing to submit a PR to fix this issue if you're OK with my proposition.

**Comment by cumany** [comment]
Thank you for pointing out this issue. The new version has been fixed. I'm not sure if the fix meets your expectations. Also,  welcome to submit a pull request anytime.

**Comment by s4my** [comment]
Sure, but you introduced a bad styling for the hover style of the buttons. I think you're using a custom theme or something that is distorting your testing. This is how the hover style look on default style:

![et](https://github.com/PKM-er/obsidian-editing-toolbar/assets/16526701/6828b0d4-061b-46c7-98f6-7ecf9f6a37e2)

Sub-items have a different style too. 
I fixed the issue with the PR #147
