### ISSUE TITLE
更新到最新版2.4.12后，工具栏显示异常

### ISSUE THREAD

**Issue by chen-jingliang** [PKM-er/obsidian-editing-toolbar#151]
**Describe the bug**
更新到最新的2.4.12版本后，选择tiny样式，工具栏显示异常，如下图

**To Reproduce**
只要工具栏显示即出现异常

**Expected behavior**
修正BUG，正常显示

**Screenshots**
<img width="417" alt="SCR-20240406-sdlr" src="https://github.com/PKM-er/obsidian-editing-toolbar/assets/28627641/d6334daa-b03b-4536-b58f-d666da0d3af6">

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser chrome 
 - Version 14.4.1

**Comment by cumany** [comment]
反写反馈 下个版本修复

**Comment by cumany** [comment]
fixed
