### ISSUE TITLE
Error message in console: Uncaught TypeError: Cannot read properties of null (reading 'containerEl')

### ISSUE THREAD

**Issue by merlinuwe** [PKM-er/obsidian-editing-toolbar#157]
Thanks for your great plugin.

Since yesterday I see this message in the console:

![image](https://github.com/PKM-er/obsidian-editing-toolbar/assets/4138869/e36b0471-70dd-4a25-89a5-da92a0c6a478)

I guess it has something to do with your latest update.

**Comment by cumany** [comment]
fixed
