### ISSUE TITLE
add check list

### ISSUE THREAD

**Issue by OLH21** [PKM-er/obsidian-editing-toolbar#82]
How is it possible to add check list in the bullet list drop down ?
Also when you delete a build in command how is it possible to add it back ?
Thanks this is one of my favorite Obsidian pluggin so far

**Comment by nightgolfer** [comment]
I'm not sure about check lists in the bullets dropdown, ou can add check lists by clicking the ( + ) next to Editing Toolbar Commands in the plugin settings, and choosing "Toggle Checkbox Status" ☑️

It doesn't seem like there is a way to restore the default buttons when deleted (other than deleting the plugin and re-installing), but you can just add the desired functionality back by the same method as stated above, and picking the functionality you want.

**Comment by OLH21** [comment]
I mean you have "bullet list" and "numbered list" but you don't have " check box list" ie "- [ ]" list in mark down .
There is no "Toggle Checkbox Status" in the command list and i don't see how this would add a checkbox ...

**Comment by robross0606** [comment]
Editing the toolbar commands doesn't seem to work.  I can add new ones to the bottom.  But the second I drag anything around, the whole "Editing Toolbar commands" section kinda freezes up and none of the edits are saved if I exit the area.  I can't even reorder toolbar commands with drag and drop.

**Comment by cumany** [comment]
This has been fixed in the new version
