### ISSUE TITLE
插件安装后页面布局错乱

### ISSUE THREAD

**Issue by murazi** [PKM-er/obsidian-editing-toolbar#84]
![image.png](https://s2.loli.net/2023/06/14/YPy2dx7HfUSBul4.png)

第一次安装，ob版本1.3.5

使用默认主题，没有自定义css，比较干净的环境下
不知道什么问题

**Comment by cumany** [comment]
卸载插件重试 看样子是样式文件冲突

**Comment by murazi** [comment]
是的，重新安装过2次后解决了，可能由于网络不畅，安装文件不完整导致，过程中一直都是默认模板和默认CSS样式，总归是解决了
